### ISSUE TITLE
[SUGGESTION] Remove String constant from BetterUI

### ISSUE THREAD

**Issue by LeStegii** [kettingpowered/KettingCore#1]
# Suggestion

Currently, the title printed by BetterUI is a string constant, which makes it hard to reuse the BetterUI class for other projects (e.g. for something like a neoforge version). This could be replaced by providing the String in a resource file or setting it with a setter method.

An even cleaner way would be to split BetterUI and KettingCore, since anyone wanting to use BetterUI would have to copy the BetterUI class, edit its content and repackage it in their own source code. However, I don't really see anyone using that class since it is very specific.

**Comment by JustRed23** [comment]
Not gonna do this as KettingCore is made to be only used on Ketting servers, the BetterUI class is practically deprecated here since it now gets used in KettingLauncher, this is just here for backwards compatibility
